source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'qjson', :path => File.expand_path(File.dirname(__FILE__) + "/../../")
gem 'riot', :group => "test"

gem "oj"
gem "guard"
gem "guard-rake"
